# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '8080:80'
    env_file:
      - docker.env
    volumes:
      - .docker/data/pgadmin:/root/.pgadmin
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
